sudo: required
language: generic

services:
    - docker

before_install:
  - docker build -t amitbiderman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amitbiderman/react-test npm test


after_success:
  - docker build -t amitbiderman/client ./client
  - docker build -t amitbiderman/nginx ./nginx
  - docker build -t amitbiderman/server ./server
  - docker build -t amitbiderman/worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub
  - docker push amitbiderman/client
  - docker push amitbiderman/nginx
  - docker push amitbiderman/server
  - docker push amitbiderman/worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-300699012348'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY